# Generated by Django 5.2.4 on 2025-07-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplierorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='status',
        ),
    ]
